services:
  - type: web
    name: notebookhub-backend
    env: node
    rootDir: backend
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && node dist/server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000 